version: "3.9"

services:
  # ---------- DB SQL : Postgres ----------
  db:
    image: postgres:16
    container_name: cloud_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

   # ---------- Zookeeper (Confluent) ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # ---------- Kafka (Confluent) ----------
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # ---------- (2) API dâ€™ingestion ----------
  ingest_api:
    build: ./ingest_api
    container_name: ingest_api
    environment:
      KAFKA_BOOTSTRAP: kafka:19092   # <--- AU LIEU DE kafka:9092
      KAFKA_TOPIC: temperatures
    depends_on:
      - kafka
    ports:
      - "8000:8000"

  # ---------- (3) Saver : consumer Kafka -> Postgres ----------
  measurement_saver:
    build: ./measurement_saver
    container_name: measurement_saver
    environment:
      KAFKA_BOOTSTRAP: kafka:19092
      KAFKA_TOPIC: temperatures
      DB_HOST: db
      DB_NAME: monitoring
      DB_USER: app_user
      DB_PASSWORD: app_password
    depends_on:
      - kafka
      - db

  # ---------- (4) Admin API ----------
  admin_api:
    build: ./admin_api
    container_name: admin_api
    environment:
      DB_HOST: db
      DB_NAME: monitoring
      DB_USER: app_user
      DB_PASSWORD: app_password
    depends_on:
      - db
    ports:
      - "8001:8000"

  # ---------- (1) Sensor generator ----------
  sensor_gen:
    build: ./sensor_gen
    container_name: sensor_gen
    environment:
      INGEST_URL: http://host.docker.internal:8000/measurements
    depends_on:
      - ingest_api

volumes:
  db_data: